### ISSUE TITLE
Integration in Crowdin is missing

### ISSUE THREAD

**Issue by prathers** [datareporter-gmbh/typo3-webcare#1]
The integration to the repository is missing in Crowdin: https://crowdin.com/project/typo3-extension-webcare/apps

**Comment by liayn** [comment]
@prathers I have access to the crowdin project, but I can't link it here, as crowdin only lists my personal repositories.

**Comment by prathers** [comment]
When you say *personal* you mean *private*?

**Comment by liayn** [comment]
No, only those repos which reside directly on my account. It does not show me those located in organisations.

**Comment by prathers** [comment]
Okay, I'll have a chat with the Crowdin team and will return to you

**Comment by prathers** [comment]
![Uploading SCR-20240312-tub.png…]()

**Comment by prathers** [comment]
![SCR-20240312-tub](https://github.com/datareporter-gmbh/typo3-webcare/assets/3508890/42dce2f0-7901-4112-bd09-d367cbe4c376)

**Comment by liayn** [comment]
I'm aware of that. But I'm pretty sure the problem is that crowdin as an OAuth app does not have access to the organisation.
I'll request that.

**Comment by liayn** [comment]
Access was granted, and integration is up.

**Comment by prathers** [comment]
How did you get around the Organisation access? I have another developer with the same problem. He only gets access to his personal github

**Comment by liayn** [comment]
I requested the access, and it was granted.

* https://github.com/settings/applications
* "Authorized OAuth Apps"
* Select crowdin

![gh](https://github.com/datareporter-gmbh/typo3-webcare/assets/222377/8500d770-e03c-4462-a836-0782536ef4ac)

**Comment by prathers** [comment]
Great! Thanks
